---
- name: Add repository
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    file: kubernetes.repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 
    gpgcheck: no

- name: Install kubectl
  yum:
    name:
      - kubectl
    state: present
